#!/usr/bin/env bash
# Script that transfers a file from our client to a server

# Check for correct usage
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  else
    # Transfer file using scp
    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3"@"$2":"~/"
fi
