#!/usr/bin/env bash
# Install nginx on web server listening on port 80 
# and returns page containing Hello World

sudo apt-get -y update

sudo apt-get install -y nginx

echo "
server {
    listen 80;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location = / {
        echo "Hello World!";
    }
}" > /etc/nginx/nginx.conf

sudo service nginx start
