#!/usr/bin/env bash
# Install nginx on web server listening on port 80 
# and returns page containing Hello World

sudo apt-get -y update

sudo apt-get install -y nginx

if [ $? -eq 0 ]; then
    # Configure Nginx
    echo -e "
    events {
    
    }

    http {
        server {
            listen 80;
            location / {
            }
        }
    }" | sudo tee /etc/nginx/nginx.conf > /dev/null
    
    echo 'Hello World!' > /var/www/html/index.html
    sudo service nginx start

    if [ $? -ne 0 ]; then
        echo "Problem starting nginx"
        exit 1
    fi
else
    echo "Could not install nginx"
    exit 1
fi

exit 0
