#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page.


sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://www.my80stv.com;
    }
}" > "/etc/nginx/sites-available/default"
sudo nginx -s reload 
