#!/usr/bin/env bash
# Configure web-02 similar to web-01

sudo apt-get update
sudo apt-get install -y nginx

sudo touch /var/www/html/index.html /var/www/html/404.html
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html/;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.my80stv.com;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/html/;
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo nginx -s reload
