#!/usr/bin/env bash
# Backup database using sqldump and compress it into tar.gz file

FILENAME=$(date +'%d-%m-%Y')
BACKUPFILE="$FILENAME.tar.gz"

mysqldump --all-databases -uroot -p"$1" > backup.sql
tar -cvzf $BACKUPFILE backup.sql
