#!/bin/env bash
# Edit the configuration file to listen on port 80
sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/#\s*server_name\s*_/server_name _/g' /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
