#!/usr/bin/env bash
# Edit the configuration file to listen on port 80
nginx_config="/etc/nginx/sites-enabled/default"
port_old="8080"
port_new="80"

sudo sed -i "s/$port_old/$port_new/g" "$nginx_config"
sudo service nginx restart
