#!/usr/bin/env bash
# displays the contents of the file `/etc/passwd`
# displays only username, user id, Home directory path for the user

while read -r passwd;
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
