#!/usr/bin/env bash
# Install and configure firewall so that it blocks incoming traffic
# except 22(SSH), 443(HTTPS SSL), 80(HTTP)

sudo apt-get install -y ufw

# Use IPV6
sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

sudo ufw enable 

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
